<?php

declare(strict_types=1);

require dirname(__DIR__) . '/_bootstrap.php';

ApiAuth::requireUser(['admin', 'staff']);

$id = (int) ($_GET['id'] ?? 0);

if ($id <= 0) {
    ApiResponse::error('Fee id is required.', 422);
}

$fee = (new Fee())->find($id);

if (!$fee) {
    ApiResponse::error('Fee record not found.', 404);
}

$downloadUrl = asset('api/fees/receipt.php?id=' . $id . '&download=1');

if (isset($_GET['download']) && $_GET['download'] === '1') {
    $tcpdfPath = app_config('base_path') . '/tcpdf/tcpdf.php';

    if (!is_file($tcpdfPath)) {
        ApiResponse::error('TCPDF library was not found.', 500);
    }

    require_once $tcpdfPath;

    $pdf = new TCPDF();
    $pdf->SetCreator(app_config('app_name'));
    $pdf->SetTitle('Fee Receipt');
    $pdf->AddPage();

    $html = '
        <h2 style="text-align:center;">' . e(app_config('app_name')) . '</h2>
        <p><strong>Receipt Date:</strong> ' . date('d M Y') . '</p>
        <hr>
        <p><strong>Student:</strong> ' . e($fee['student_name']) . '</p>
        <p><strong>Course:</strong> ' . e($fee['course_name']) . '</p>
        <p><strong>Total Fees:</strong> ' . e(currency($fee['total_fees'])) . '</p>
        <p><strong>Paid:</strong> ' . e(currency($fee['paid'])) . '</p>
        <p><strong>Remaining:</strong> ' . e(currency($fee['remaining'])) . '</p>
        <p><strong>Status:</strong> ' . e($fee['status']) . '</p>
        <p><strong>Last Payment Date:</strong> ' . e((string) $fee['last_payment_date']) . '</p>
        <hr>
        <p style="color:#0f766e;">Generated by Coaching ERP API.</p>
    ';

    $pdf->writeHTML($html);
    $pdf->Output('fee_receipt_' . $fee['id'] . '.pdf', 'I');
    exit;
}

ApiResponse::success('Receipt URL generated successfully.', [
    'fee_id' => $id,
    'download_url' => $downloadUrl,
]);
